### ISSUE TITLE
FileNotFoundError, PermissionError, Segmentation Fault error on running the raiden-installer binary

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden-installer#7]
Steps By which i get the error.
1. `git clone git@github.com:raiden-network/raiden-installer.git`
2. `pip install -r requirements-dev.txt`
3. `python setup.py install`
4. Run `make binary`
```
(raiden_env) [krishna@krishna-pc raiden-installer]$ make binary
pyinstaller raideninstaller/__main__.py --clean --onefile --name raiden-installer-LATEST
make: pyinstaller: Command not found
make: *** [Makefile:18: binary] Error 127
```
5. `pip install pyinstaller`
6. Running `make binary` again
```
(raiden_env) [krishna@krishna-pc raiden-installer]$ make binary
pyinstaller raideninstaller/__main__.py --clean --onefile --name raiden-installer-LATEST
33 INFO: PyInstaller: 3.4
33 INFO: Python: 3.7.2
33 INFO: Platform: Linux-5.0.1-arch1-1-ARCH-x86_64-with-arch
34 INFO: wrote /home/krishna/raidenforked/raiden-installer/raiden-installer-LATEST.spec
35 INFO: UPX is not available.
35 INFO: Removing temporary files and cleaning cache in /home/krishna/.cache/pyinstaller
36 INFO: Extending PYTHONPATH with paths
['/home/krishna/raidenforked/raiden-installer',
 '/home/krishna/raidenforked/raiden-installer']
36 INFO: checking Analysis
36 INFO: Building Analysis because Analysis-00.toc is non existent
36 INFO: Initializing module dependency graph...
38 INFO: Initializing module graph hooks...
38 INFO: Analyzing base_library.zip ...
1267 INFO: running Analysis Analysis-00.toc
1283 INFO: Caching module hooks...
1285 INFO: Analyzing /home/krishna/raidenforked/raiden-installer/raideninstaller/__main__.py
1668 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
3651 INFO: Processing pre-safe import module hook   six.moves
4209 INFO: Loading module hooks...
4209 INFO: Loading module hook "hook-cryptography.py"...
4326 INFO: Loading module hook "hook-certifi.py"...
4328 INFO: Loading module hook "hook-xml.py"...
4385 INFO: Loading module hook "hook-encodings.py"...
4427 INFO: Looking for ctypes DLLs
4433 INFO: Analyzing run-time hooks ...
4438 INFO: Looking for dynamic libraries
5048 INFO: Looking for eggs
5048 INFO: Using Python library /usr/lib/libpython3.7m.so.1.0
5059 INFO: Warnings written to /home/krishna/raidenforked/raiden-installer/build/raiden-installer-LATEST/warn-raiden-installer-LATEST.txt
5100 INFO: Graph cross-reference written to /home/krishna/raidenforked/raiden-installer/build/raiden-installer-LATEST/xref-raiden-installer-LATEST.html
5112 INFO: checking PYZ
5112 INFO: Building PYZ because PYZ-00.toc is non existent
5112 INFO: Building PYZ (ZlibArchive) /home/krishna/raidenforked/raiden-installer/build/raiden-installer-LATEST/PYZ-00.pyz
5469 INFO: Building PYZ (ZlibArchive) /home/krishna/raidenforked/raiden-installer/build/raiden-installer-LATEST/PYZ-00.pyz completed successfully.
5474 INFO: checking PKG
5474 INFO: Building PKG because PKG-00.toc is non existent
5474 INFO: Building PKG (CArchive) PKG-00.pkg
8748 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
8750 INFO: Bootloader /home/krishna/Envs/raiden_env/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-64bit/run
8750 INFO: checking EXE
8750 INFO: Building EXE because EXE-00.toc is non existent
8750 INFO: Building EXE from EXE-00.toc
8750 INFO: Appending archive to ELF section in EXE /home/krishna/raidenforked/raiden-installer/dist/raiden-installer-LATEST
8786 INFO: Building EXE from EXE-00.toc completed successfully.

```
7. Navigating to `dist` folder and running the generated binary 

```
(raiden_env) [krishna@krishna-pc raiden-installer]$ cd dist/
(raiden_env) [krishna@krishna-pc dist]$ ls
raideninstaller-0.0.1-py3.7.egg  raiden-installer-LATEST
(raiden_env) [krishna@krishna-pc dist]$ ./raiden-installer-LATEST 
Choose a installation directory: [/opt/raiden]~/raideninstallertest  

Input accepted. Continuing..

Step 1: Raiden Binary Setup


Traceback (most recent call last):
  File "raideninstaller/__main__.py", line 32, in <module>
  File "raideninstaller/steps/raiden.py", line 20, in __init__
  File "pathlib.py", line 1241, in mkdir
FileNotFoundError: [Errno 2] No such file or directory: '/opt/raiden/download'
[8099] Failed to execute script __main__
(raiden_env) [krishna@krishna-pc dist]$ ls /opt/raiden
ls: cannot access '/opt/raiden': No such file or directory
(raiden_env) [krishna@krishna-pc dist]$ ./raiden-installer-LATEST 
Choose a installation directory: [/opt/raiden]

Input accepted. Continuing..
Traceback (most recent call last):
  File "raideninstaller/__main__.py", line 23, in <module>
  File "pathlib.py", line 1241, in mkdir
PermissionError: [Errno 13] Permission denied: '/opt/raiden'
[8333] Failed to execute script __main__
```
Actually above are the errors that i got on my second time installing it. The first time I tried i got [these](https://gist.github.com/agatsoh/35938d3327afe54b9f31de18eb1bf403) errors.

**Comment by nlsdfnbch** [comment]
Fixed in 7bd983b07b3c72913e0a016dd45fce85fab3fc4e - giving a custom install dir should now correctly use that dir.
